name: gh-pages deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: EdricChan03/action-build-deploy-ghpages@v3.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: echo DEPLOY_SUCCESS
