name: gh-pages deploy

on:
  # pull_request:
  #   branches: ['main']
  #   types:
  #     - closed
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    # if_merged:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EdricChan03/action-build-deploy-ghpages@v3.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo DEPLOY_SUCCESS
